name: Bump Version
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          npm version ${{ inputs.bumpType }} -m "Release version %s"
          version=$(node -p "require('./package.json').version.replace('\n', ''))")
          echo "current_version=${version}" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: |
            "Release version ${{ env.current_version }}"
