name: Bump Version
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add user
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Make Commit
        run: |  
          version=$(npm version ${{ inputs.bumpType }} -m "Release version %s")
          echo "current_version=${version#?}" >> $GITHUB_ENV

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Release version ${{ env.current_version }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          github-token: ${{ secrets.AUTOMERGE_APPROVER }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          method: squash
          repo: juliangruber/octokit-action
