name: Bump Version
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add user
        run: |
          git config user.name ${{ github.triggering_actor }}
          git config user.email ${{ github.triggering_actor }}@gh-workflow-no-reply.com

      - name: Make Commit
        run: |
          version=$(npm version ${{ inputs.bumpType }} -m "Release version %s")
          echo "current_version=${version#?}" >> $GITHUB_ENV

      - name: Push commit
        run: git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Create Pull Request
#        id: create-pr
#        uses: peter-evans/create-pull-request@v4
#        with:
#          title: Release version ${{ env.current_version }}
#          delete-branch: true
#          token: ${{ secrets.GITHUB_TOKEN }}
