name: Bump Version
on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Make Commit
        uses: actions/checkout@v3
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          version=$(npm version ${{ inputs.bumpType }} -m "Release version %s")
          echo "current_version=${version#?}" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Release version ${{ env.current_version }}
